[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "doctransmittal"
version = "0.1.0"
description = "Document Transmittal System"
authors = [{ name="William Arnott"}]

[tool.setuptools.packages.find]
include = ["doctransmittal_sub*"]
